### ISSUE TITLE
PlayerMoveEvent failure (NPE)

### ISSUE THREAD

**Issue by SlimeDog** [Mr-EmPee/MysticalBarriers#1] opened 2022-10-29 21:29 UTC
Java 19.0
Spigot 1.19.2-3604
LuckPerms 5.4.52
ProtocolLib 5.0.0-b602
MysticalBarriers v1.4.0

Changing LuckPerms group, changes permissions from
`mysticalbarriers.bypass.lobby-yellowdog: true`
to
`mysticalbarriers.bypass.lobby-yellowdog: false`
which should cause the barriers to appear. They do not.

Please update to support MC 1.19.2

```
[14:12:24] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to MysticalBarriers v1.4.0
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1353) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3604-Spigot-1aec3fc-f43634a]
        at net.minecraft.network.protocol.game.PacketPlayInFlying.a(SourceFile:114) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3604-Spigot-1aec3fc-f43634a]
        at net.minecraft.network.protocol.game.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:16) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3604-Spigot-1aec3fc-f43634a]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:31) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3604-Spigot-1aec3fc-f43634a]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3604-Spigot-1aec3fc-f43634a]
        at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:157) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3604-Spigot-1aec3fc-f43634a]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3604-Spigot-1aec3fc-f43634a]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1150) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3604-Spigot-1aec3fc-f43634a]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3604-Spigot-1aec3fc-f43634a]
        at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:131) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3604-Spigot-1aec3fc-f43634a]
        at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1129) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3604-Spigot-1aec3fc-f43634a]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1122) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3604-Spigot-1aec3fc-f43634a]
        at net.minecraft.util.thread.IAsyncTaskHandler.bq(SourceFile:116) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3604-Spigot-1aec3fc-f43634a]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1105) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3604-Spigot-1aec3fc-f43634a]
        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1017) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3604-Spigot-1aec3fc-f43634a]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:293) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3604-Spigot-1aec3fc-f43634a]
        at java.lang.Thread.run(Thread.java:1589) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "Object.equals(Object)" because the return value of "ml.empee.mysticalBarriers.model.Barrier.getWorld()" is null
        at ml.empee.mysticalBarriers.services.components.BarrierBlocksSpawner.spawnBarrier(BarrierBlocksSpawner.java:48) ~[MysticalBarriers-1.4.0.jar:?]
        at ml.empee.mysticalBarriers.services.components.BarrierBlocksSpawner.onPlayerMove(BarrierBlocksSpawner.java:41) ~[MysticalBarriers-1.4.0.jar:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        ... 20 more
```

**Comment by Mr-EmPee** [comment] 2022-11-01 11:09
I'm unable to reproduce the bug.

Minecraft 1.19 isn't still officially supported by this plugin because it depends on ProtocolLib and at the moment it's not available a stable version that support 1.19

**Comment by SlimeDog** [comment] 2022-11-01 13:57
It is an unfortunate feature of the current world that development builds are typical, long after the relevant MC version is stable. The list of major plugins that do this is long, and (as you note) includes ProtocolLib.

At least 20 of the plugins we test rely on ProtocolLib, which works fine with all of them (except MB). Please reconsider. This issue still exists with MysticalBarriers 1.5.0 and the listed (latest) development ProtocolLib and Spigot.

**Comment by Mr-EmPee** [comment] 2022-11-01 21:10
1.19.2 support was already planned, whenever I have time I'm gonna work on it.

**Comment by SlimeDog** [comment] 2022-11-01 21:19
Great, thanks.

**Comment by Mr-EmPee** [comment] 2022-11-09 13:35
I'm gonna close this issue given that the plugin atm doesn't support 1.19

**Closed as completed by Mr-EmPee** 2022-11-09 13:35 UTC

**Comment by SlimeDog** [comment] 2022-11-09 15:21
Closed as "completed" ? Shouldn't you leave the issue open until it does support 1.19.x ?

**Comment by Mr-EmPee** [comment] 2022-11-09 19:40
I opened a new issue regarding 1.19 support. This is merely an effect that the plugin wasn't intended for 1.19 servers.

**Comment by SlimeDog** [comment] 2022-11-09 20:04
OK, thanks.
